SELECT TOP (1000) [Id]
      ,[CustomerId]
      ,[ProjectId]
      ,[Cat_MentalHealth]
      ,[Cat_PhysicalHealth]
      ,[Cat_Employment]
      ,[Cat_SocialConnection]
      ,[Cat_Culture]
      ,[Cat_Housing]
      ,[Cat_Religious]
      ,[Cat_Environment]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc]
  FROM [dbo].[OutcomeRecord]