SELECT TOP (1000) [Id]
      ,[CustomerId]
      ,[Step1]
      ,[Step2]
      ,[Step3]
      ,[Step4]
      ,[Step5]
      ,[Step6]
      ,[ProjectId]
      ,[OutputsId]
      ,[OutcomesId]
      ,[CaseStudyID]
      ,[OutcomeId]
  FROM [dbo].[Steps]